name: cashier_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  barcode_scan2: ^4.3.3
  dtd: ^4.0.0
  flutter:
    sdk: flutter
  flutter_lints: ^6.0.0
  google_fonts: ^6.3.3
  google_generative_ai: ^0.4.5
  image_picker: ^1.1.2
  intl: ^0.19.0
  json_rpc_2: ^4.0.0
  path: ^1.9.1
  path_provider: ^2.1.3
  provider: ^6.1.2
  sqflite: ^2.3.3 # flutter pub add sqflite
  sqlite3: ^3.1.1
  stack_trace: ^1.12.1
  url_launcher: ^6.3.2
  web: ^1.1.1
  sqflite_common_ffi: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/faq.md
